apiVersion: v1
kind: Pod
metadata:
  labels:
    app: turn
  name: turn
spec:
  hostNetwork: true
  containers:
    - name: coturn
      image: docker.io/coturn/coturn:latest
      securityContext:
        capabilities:
          drop:
          - CAP_MKNOD
          - CAP_NET_RAW
          - CAP_AUDIT_WRITE
      volumeMounts:
      - name: config
        mountPath: /etc/coturn/turnserver.conf
  volumes:
  - name: config
    hostPath:
      path: /data/matrix/coturn.conf
