CREATE USER discord WITH PASSWORD 'DISCORD';
CREATE DATABASE discord;
GRANT ALL PRIVILEGES ON DATABASE discord TO discord;

CREATE USER instagram WITH PASSWORD 'INSTAGRAM';
CREATE DATABASE instagram;
GRANT ALL PRIVILEGES ON DATABASE instagram TO instagram;

CREATE USER linkedin WITH PASSWORD 'LINKEDIN';
CREATE DATABASE linkedin;
GRANT ALL PRIVILEGES ON DATABASE linkedin TO linkedin;

CREATE USER signal WITH PASSWORD 'SIGNAL';
CREATE DATABASE signal;
GRANT ALL PRIVILEGES ON DATABASE signal TO signal;

CREATE USER whatsapp WITH PASSWORD 'WHATSAPP';
CREATE DATABASE whatsapp;
GRANT ALL PRIVILEGES ON DATABASE whatsapp TO whatsapp;